spring.application.name=Back_FirmaTrack
server.port=8888

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/firmatrack
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger pour tester les api
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuration stockage local images
file.upload-dir=./uploads